language: python
services:
  - docker
python:
  - "3.6"
  - "3.7-dev" # only 3.7-dev is supported currently
install:
  - pip install -r requirements.txt
script:
  - python3.6 test.py
  - touch web/config.ini githublinker.db # create some empty files so that docker compose does not fail
  - docker-compose build # test that the docker image can be built