version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - data-volume:/app/data
  bot:
    build: ./bot
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - data-volume:/app/data
    depends_on:
      - web

volumes:
  data-volume: